platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'LoginExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'SnapKit', '~> 5.6.0'
  pod 'Then'
  
  # Login
  pod 'naveridlogin-sdk-ios'
  pod 'KakaoSDK'
  
  post_install do |installer_representation|
      installer_representation.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
              config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
          end
      end
  end

end
